# Generated by Django 6.0.2 on 2026-03-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_producer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='contact_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
