# Generated by Django 6.0.2 on 2026-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation_name',
            field=models.CharField(blank=True, default='', help_text='Organisation/institution name (for community groups and restaurants).', max_length=255),
        ),
    ]
