# Generated by Django 6.0.2 on 2026-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='farm_story',
            field=models.TextField(blank=True, default='', help_text="The farm's story, background, and mission"),
        ),
    ]
