# Generated by Django 6.0.2 on 2026-03-06 19:11

import accounts.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal required for this producer (0 = no minimum).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('producer', 'Producer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
