# Generated by Django 6.0.2 on 2026-05-07 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_alter_product_harvest_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('bulk', 'Bulk Order')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='organisation_name',
            field=models.CharField(blank=True, default='', help_text='Organisation placing the order (for community group bulk orders).', max_length=255),
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Friendly name for this recurring order (e.g. "Weekly Produce").', max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], max_length=15)),
                ('delivery_address', models.TextField()),
                ('next_delivery_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for the schedule.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('times_placed', models.PositiveIntegerField(default=0)),
                ('last_placed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to=settings.AUTH_USER_MODEL)),
                ('source_order', models.ForeignKey(blank=True, help_text='The original order this schedule was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at the time the schedule was created.', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('recurring_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.recurringorder')),
            ],
        ),
    ]
