import django, os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from decimal import Decimal
from accounts.models import User, ProducerProfile
from products.models import Category, Product

# Clear existing data
Product.objects.all().delete()
Category.objects.all().delete()
ProducerProfile.objects.all().delete()
User.objects.all().delete()

# Create admin
admin = User.objects.create_superuser(
    email='admin@bristol.ac.uk', password='admin1234',
    first_name='Admin', last_name='User', is_active=True, role='admin'
)

# Create producers
p1 = User.objects.create_user(
    email='green@farm.co.uk', password='test1234',
    first_name='Green', last_name='Valley',
    is_producer=True, is_active=True, role='producer'
)
p1.producer_profile.store_name = 'Green Valley Farm'
p1.producer_profile.store_description = 'Certified organic vegetables and seasonal fruits grown in the rolling hills of Somerset. Everything is hand-picked at peak ripeness and delivered within 24 hours of harvest.'
p1.producer_profile.store_contact = 'green@farm.co.uk | 01749 830 412'
p1.producer_profile.store_address = 'Passage Road Farm, Henbury, Bristol, BS10 7QR'
p1.producer_profile.farm_story = (
    'Green Valley Farm has been in the Fletcher family for four generations, stretching back to 1947 when Thomas Fletcher first broke ground on 12 acres of Somerset hillside. '
    'What started as a mixed livestock farm gradually transformed into one of the region\'s most respected organic growing operations. '
    'In 1989, Thomas\'s daughter Ruth made the bold decision to transition fully to organic methods — at a time when the word "organic" was barely understood by most consumers. '
    'Today, Ruth\'s son Daniel runs the farm alongside his partner Priya, cultivating over 60 varieties of vegetables and fruit across 38 acres. '
    'They were awarded the Soil Association\'s Farm of the Year in 2021 and supply produce to the Bristol Regional Food Network as a founding member. '
    'Their philosophy is simple: healthy soil grows healthy food, and healthy food builds healthy communities. Every seed they plant is chosen for flavour, not shelf life.'
)
p1.producer_profile.save()

p2 = User.objects.create_user(
    email='baker@artisan.co.uk', password='test1234',
    first_name='Artisan', last_name='Baker',
    is_producer=True, is_active=True, role='producer'
)
p2.producer_profile.store_name = 'Bristol Artisan Bakery'
p2.producer_profile.store_description = 'Handcrafted sourdough breads, pastries, and seasonal bakes made fresh daily in the heart of Bristol using long-fermentation techniques and locally milled flour.'
p2.producer_profile.store_contact = 'baker@artisan.co.uk | 0117 923 5501'
p2.producer_profile.store_address = '14 Stokes Croft, Bristol, BS1 3PR'
p2.producer_profile.farm_story = (
    'Bristol Artisan Bakery was born in a tiny railway arch in Stokes Croft in 2011, when head baker Marco Silva left a Michelin-starred London restaurant to pursue something more meaningful. '
    'Armed with a 200-year-old sourdough starter he carried from Portugal in a jam jar, Marco began baking 40 loaves a night and selling them at St Nicholas Market every Saturday. '
    'The queues grew so long that within two years he had outgrown the arch and moved to a purpose-built bakehouse on Stokes Croft. '
    'Today the team of seven bakers still begins work at 3am, slow-fermenting every loaf for a minimum of 18 hours. '
    'All flour is stone-milled from heritage wheat varieties grown in Wiltshire, and Marco personally visits the mill twice a year to select each batch. '
    'Nothing is rushed. Nothing is frozen. Every loaf that leaves the bakery was made by hand that morning — because Marco believes you can taste the difference, and so do we.'
)
p2.producer_profile.save()

p3 = User.objects.create_user(
    email='dairy@meadow.co.uk', password='test1234',
    first_name='Meadow', last_name='Dairy',
    is_producer=True, is_active=True, role='producer'
)
p3.producer_profile.store_name = 'Meadow Dairy Co'
p3.producer_profile.store_description = 'Farm-fresh dairy from a herd of 80 free-range Brown Swiss cows grazing the Cotswold escarpment. Unhomogenised milk, artisan cheeses, and cultured dairy products made with exceptional care.'
p3.producer_profile.store_contact = 'dairy@meadow.co.uk | 01453 860 209'
p3.producer_profile.store_address = 'Blaise Farm, Lawrence Weston Road, Bristol, BS11 0LP'
p3.producer_profile.farm_story = (
    'Meadow Dairy Co was established in 2003 by veterinarian Dr. Claire Ashton, who left her practice after becoming frustrated watching industrial dairy operations prioritise output over animal welfare. '
    'She purchased a neglected 90-acre farm on the Cotswold escarpment, restored the meadows using traditional hay-making and wildflower seeding, and introduced a small herd of Brown Swiss cattle — a heritage breed known for rich, high-protein milk. '
    'Claire\'s approach is radical by modern dairy standards: the cows are never housed overnight between April and October, calves are raised alongside their mothers for the first six months, and milking happens just once a day to reduce stress on the herd. '
    'The result is milk with a depth of flavour that regularly stops first-time customers in their tracks. '
    'The cheese operation began almost by accident — a surplus of summer milk led Claire to experiment with a soft Camembert-style recipe, which promptly won a gold medal at the British Cheese Awards. '
    'That was 2009. Since then, Meadow Dairy has won 23 national awards and supplies some of Bristol\'s finest restaurants.'
)
p3.producer_profile.save()

p4 = User.objects.create_user(
    email='seafood@harbour.co.uk', password='test1234',
    first_name='Harbour', last_name='Fresh',
    is_producer=True, is_active=True, role='producer'
)
p4.producer_profile.store_name = 'Harbour Fresh Seafood'
p4.producer_profile.store_description = 'Day-boat fish and shellfish landed fresh at Portishead and delivered to your door the same morning. Sustainably caught using traditional line and pot methods — never trawled.'
p4.producer_profile.store_contact = 'seafood@harbour.co.uk | 01275 841 730'
p4.producer_profile.store_address = 'Avonmouth Dock Road, Avonmouth, Bristol, BS11 9YA'
p4.producer_profile.farm_story = (
    'Harbour Fresh was founded in 2016 by brothers Joe and Sam Trevithick, third-generation fishermen whose grandfather first worked the Bristol Channel in the 1960s on a wooden day-boat named The Margery. '
    'After years of watching large trawlers devastate local fish populations, Joe and Sam decided to do things differently. '
    'They operate two small vessels — The Margery II and The Saltwater — using only hand lines, crab pots, and sustainable gill nets that are checked daily. '
    'Every species they catch is assessed against the Marine Conservation Society\'s Good Fish Guide before it joins their range. '
    'On days when the catch doesn\'t meet their standards, they don\'t sell. Simple as that. '
    'The brothers expanded into home delivery in 2019 after Bristol customers kept asking where they could buy the same fish the restaurants were getting. '
    'Today they deliver across the Bristol postcode area by 9am, with the fish having been in the water less than 12 hours earlier. '
    '"The sea gives us everything," Joe says. "The least we can do is take care of it."'
)
p4.producer_profile.save()

p5 = User.objects.create_user(
    email='butcher@bristol.co.uk', password='test1234',
    first_name='Bristol', last_name='Butcher',
    is_producer=True, is_active=True, role='producer'
)
p5.producer_profile.store_name = 'Bristol Quality Meats'
p5.producer_profile.store_description = 'Traditionally reared beef, lamb, and chicken from named farms across Somerset and Dorset. Dry-aged on-site for a minimum of 28 days. No shortcuts, no compromises.'
p5.producer_profile.store_contact = 'butcher@bristol.co.uk | 0117 954 8820'
p5.producer_profile.store_address = '67 Whiteladies Road, Clifton, Bristol, BS8 2NT'
p5.producer_profile.farm_story = (
    'Bristol Quality Meats has been a fixture on Whiteladies Road since 1978, when master butcher Roy Harding opened the shop with £800 in savings and a firm handshake agreement with two Somerset farmers. '
    'Nearly five decades later, Roy\'s granddaughter Imogen runs the business with the same philosophy: know exactly where every animal comes from, how it was raised, and what it ate. '
    'Every farm that supplies Bristol Quality Meats is visited in person at least twice a year. Imogen refuses to stock anything from operations she wouldn\'t be comfortable showing to a customer. '
    'All beef is dry-aged for a minimum of 28 days in their on-site Himalayan salt chamber — a method that concentrates flavour and tenderises the meat naturally without any additives. '
    'The chicken comes exclusively from a single farm in the Mendip Hills where birds are slow-grown over 81 days — more than double the industry standard — and spend their lives on pasture. '
    'In an era of supermarket convenience, Bristol Quality Meats is a reminder that the best food has a name, a face, and a postcode.'
)
p5.producer_profile.save()

# Create customer
c1 = User.objects.create_user(
    email='customer@test.com', password='test1234',
    first_name='Jane', last_name='Smith',
    is_active=True, role='customer', customer_role='individual',
    postcode='BS8 1TH', address='42 Park Street, Bristol'
)

p6 = User.objects.create_user(
    email='orchard@wyevalley.co.uk', password='test1234',
    first_name='Wye', last_name='Valley',
    is_producer=True, is_active=True, role='producer'
)
p6.producer_profile.store_name = 'Wye Valley Orchard'
p6.producer_profile.store_description = 'Heritage fruit orchard nestled in the Wye Valley AONB. Over 80 varieties of apples, pears, cherries and plums grown using traditional low-intervention methods on ancient limestone soils.'
p6.producer_profile.store_contact = 'orchard@wyevalley.co.uk | 01600 712 340'
p6.producer_profile.store_address = 'Long Ashton Orchards, Long Ashton, Bristol, BS41 9DP'
p6.producer_profile.farm_story = (
    'Wye Valley Orchard was established in 1923 by the Griffiths family on a south-facing limestone escarpment above the River Wye. '
    'The farm passed through four generations before arriving with current owner Huw Griffiths in 2008, who made the bold decision to abandon commercial apple varieties entirely and return the orchard to its heritage roots. '
    'Today, Huw tends over 80 varieties of fruit — many of them pre-Victorian cultivars that had almost vanished from British agriculture. '
    'You\'ll find names like "Slack-ma-Girdle", "Foxwhelp", and "Chisel Jersey" alongside better-known varieties. '
    'Nothing is sprayed. Nothing is forced. The orchard runs on patience, rainfall, and the same limestone soil that has been feeding fruit trees here for over a century. '
    'Huw says the orchard teaches him something new every year — and he\'s been listening carefully for the past 16.'
)
p6.producer_profile.save()

p7 = User.objects.create_user(
    email='herbs@somersetgarden.co.uk', password='test1234',
    first_name='Somerset', last_name='Garden',
    is_producer=True, is_active=True, role='producer'
)
p7.producer_profile.store_name = 'Somerset Herb Garden'
p7.producer_profile.store_description = 'Specialist grower of culinary herbs, salad leaves, and edible flowers on the Somerset Levels. Cut-to-order and delivered the same day for unrivalled freshness.'
p7.producer_profile.store_contact = 'herbs@somersetgarden.co.uk | 01458 831 205'
p7.producer_profile.store_address = 'Barton Hill Market Garden, St George, Bristol, BS5 9RD'
p7.producer_profile.farm_story = (
    'Somerset Herb Garden was founded in 2014 by former chef Amara Osei, who spent fifteen years cooking in restaurant kitchens across Europe before deciding she was tired of working with herbs that had travelled further than she had. '
    'She returned to the Somerset Levels — where she grew up — and converted a two-acre market garden into one of the most diverse herb growing operations in the South West. '
    'Amara grows over 120 varieties of culinary herbs, salad leaves, and edible flowers, many of them rare cultivars she sources from specialist seed libraries in France and Italy. '
    'Everything is cut to order, meaning nothing sits in cold storage. Chefs across Bristol have told her they can taste the difference — and so can home cooks. '
    '"A herb that was in the ground this morning tastes completely different from one that\'s been in a plastic bag for a week," she says. "Once you know that, you can\'t go back."'
)
p7.producer_profile.save()

p8 = User.objects.create_user(
    email='honey@mendiphive.co.uk', password='test1234',
    first_name='Mendip', last_name='Hive',
    is_producer=True, is_active=True, role='producer'
)
p8.producer_profile.store_name = 'Mendip Hive & Preserves'
p8.producer_profile.store_description = 'Raw wildflower honey and small-batch preserves made from fruit grown on the Mendip Hills. No artificial pectin, no mass production — just fruit, sugar, and decades of knowledge.'
p8.producer_profile.store_contact = 'honey@mendiphive.co.uk | 01934 742 891'
p8.producer_profile.store_address = 'Redland Green Road, Redland, Bristol, BS6 6TH'
p8.producer_profile.farm_story = (
    'Mendip Hive & Preserves began with a single beehive in a back garden in 2007. Its owner, retired schoolteacher Margaret Vowles, started keeping bees as a retirement hobby and quickly became obsessed. '
    'By 2012 she had 24 hives spread across the Mendip Hills, each positioned to take advantage of different wildflower meadows — heather moorland, limestone grassland, and ancient hedgerow. '
    'The honey from each site tastes completely different, and Margaret sells them separately so customers can compare. '
    'The preserves operation came later, born out of a need to use surplus fruit from neighbouring farms that would otherwise go to waste. '
    'Margaret makes every jar herself using fruit harvested within 10 miles of her cottage, and she refuses to use commercial pectin or artificial setting agents. '
    '"A good jam should taste of the fruit," she says firmly. "If you have to read the ingredients to understand what\'s in it, something has gone wrong."'
)
p8.producer_profile.save()

p9 = User.objects.create_user(
    email='cheese@cliftoncreamery.co.uk', password='test1234',
    first_name='Clifton', last_name='Creamery',
    is_producer=True, is_active=True, role='producer'
)
p9.producer_profile.store_name = 'Clifton Fine Cheese'
p9.producer_profile.store_description = 'Artisan cheesemakers based in Clifton, Bristol. Specialising in soft, aged, and blue cheeses made from milk sourced exclusively from West Country farms within 30 miles.'
p9.producer_profile.store_contact = 'cheese@cliftoncreamery.co.uk | 0117 946 6120'
p9.producer_profile.store_address = '3 Princess Victoria Street, Clifton, Bristol, BS8 4BX'
p9.producer_profile.farm_story = (
    'Clifton Fine Cheese was opened in 2009 by cheesemaker Sophia Andreou, who trained under master fromager Pierre Coulon in Lyon before returning to her adopted home city of Bristol. '
    'Sophia makes all her cheeses by hand in a small dairy behind the shop on Princess Victoria Street, using milk collected three times a week from four farms in Somerset and Dorset. '
    'She refuses to use ultra-pasteurised milk, which she believes kills the flavour complexity that makes artisan cheese worth eating. '
    'Her soft Bristol Brie has become something of a local institution, regularly selling out within hours of being ready. '
    'The blue cheese — a bold, buttery variety she calls "Clifton Blue" — won a silver medal at the World Cheese Awards in 2022. '
    'Sophia says she\'s not trying to compete with French cheese. She\'s trying to make something that could only come from Bristol, from this milk, from this moment in time.'
)
p9.producer_profile.save()

p10 = User.objects.create_user(
    email='drinks@severncordial.co.uk', password='test1234',
    first_name='Severn', last_name='Cordial',
    is_producer=True, is_active=True, role='producer'
)
p10.producer_profile.store_name = 'Severn Cordial Co.'
p10.producer_profile.store_description = 'Small-batch cordials, pressed juices, and botanical drinks made from foraged and farmed ingredients along the Severn Valley. No artificial flavours, no concentrates — real fruit, real taste.'
p10.producer_profile.store_contact = 'drinks@severncordial.co.uk | 01291 623 780'
p10.producer_profile.store_address = 'The Old Brewery, Bedminster, Bristol, BS3 4AP'
p10.producer_profile.farm_story = (
    'Severn Cordial Co. was founded in 2017 by siblings Rosa and Finn Watkins in a converted watermill on the edge of Chepstow. '
    'Rosa, a trained botanist, spends the warmer months foraging elderflower, sloe, and wild blackcurrant from the hedgerows along the Severn Valley. '
    'Finn, who previously worked in craft brewing, handles the production — pressing, blending, and bottling everything by hand in small batches. '
    'Their philosophy is simple: use only what grows within walking distance, and use all of it. Excess elderflower becomes cordial, then syrup, then vinegar. Nothing is wasted. '
    'The range changes with the seasons, which means their product list looks different in February than it does in August. '
    'Regular customers say that\'s exactly the point — it\'s a drink that tells you what time of year it is.'
)
p10.producer_profile.save()

# Create categories
veg = Category.objects.create(name='Vegetables')
fruit = Category.objects.create(name='Fruit')
bread = Category.objects.create(name='Bread & Bakery')
dairy = Category.objects.create(name='Dairy')
meat = Category.objects.create(name='Meat & Poultry')
seafood = Category.objects.create(name='Seafood')
pantry = Category.objects.create(name='Pantry & Staples')
drinks = Category.objects.create(name='Drinks')
preserves = Category.objects.create(name='Preserves')

# Create products with image mappings
products_data = [
    # Green Valley Farm - Vegetables & Fruit
    {'name': 'Organic Carrots', 'description': 'Freshly harvested organic carrots, hand-pulled from Somerset hillside soil. Sweet, earthy, and sold with the tops on to show just how fresh they are.', 'price': '2.50', 'unit': 'per kg', 'stock_quantity': 100, 'organic_certified': True, 'harvest_date': '2026-03-20', 'allergens': '', 'storage_tips': 'Keep unwashed in a sealed bag in the fridge for up to 2 weeks. Trim the tops before storing to prevent moisture loss.', 'recipe_idea': 'Roast with honey and thyme at 200°C for 30 minutes, or grate raw into a Moroccan-style salad with cumin, lemon, and fresh coriander.', 'producer': p1, 'category': veg, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1447175008436-054170c2e979?w=600&q=80'},
    {'name': 'Heritage Tomatoes', 'description': 'Vine-ripened heritage tomatoes in a riot of colours — yellow, striped green, deep red, and purple. Grown slowly in our polytunnels for maximum sweetness and flavour.', 'price': '3.75', 'unit': 'per kg', 'stock_quantity': 60, 'organic_certified': True, 'harvest_date': '2026-03-22', 'allergens': '', 'storage_tips': 'Never refrigerate — store at room temperature, out of direct sunlight, stem-side down to slow ripening. Cold destroys their flavour.', 'recipe_idea': 'Slice thickly, season with flaky salt, drizzle with rapeseed oil and torn basil. Allow to sit for 10 minutes before eating — they need no more than this.', 'producer': p1, 'category': veg, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&q=80'},
    {'name': 'Fresh Spinach', 'description': 'Baby spinach leaves cut at their most tender. Washed, bagged, and ready for salads, stir-fries, or wilting into pasta. Picked on the morning of delivery.', 'price': '2.00', 'unit': 'per bag (200g)', 'stock_quantity': 80, 'organic_certified': True, 'harvest_date': '2026-03-23', 'allergens': '', 'storage_tips': 'Keep refrigerated and eat within 2–3 days of delivery. Do not wash until ready to use — excess moisture speeds up wilting.', 'recipe_idea': 'Wilt into warm garlic butter with a pinch of nutmeg and serve alongside soft-scrambled eggs, or blend raw into a green smoothie with banana and apple for a surprisingly mild result.', 'producer': p1, 'category': veg, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80'},
    {'name': 'Bramley Apples', 'description': 'Classic British cooking apples from our orchard — sharp, firm, and perfect for crumbles, pies, and sauces. They cook down beautifully into a fluffy, fragrant purée.', 'price': '3.00', 'unit': 'per kg', 'stock_quantity': 150, 'organic_certified': False, 'harvest_date': '2026-03-18', 'allergens': '', 'storage_tips': 'Store in a cool, dark place or the bottom of the fridge. They keep for 3–4 weeks if undamaged. Keep away from other fruit as they emit ethylene gas.', 'recipe_idea': 'Classic Somerset crumble: peel and slice 4 apples, toss with cinnamon and brown sugar, top with a mix of oats, butter, and flour, bake at 180°C for 35 minutes until bubbling and golden.', 'producer': p1, 'category': fruit, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&q=80'},
    {'name': 'Seasonal Veg Box', 'description': 'A hand-picked selection of whatever is at its absolute best on the farm this week — typically 6–8 varieties including roots, brassicas, and salad. No duplicates, no waste, always a surprise.', 'price': '9.50', 'unit': 'per box', 'stock_quantity': 40, 'organic_certified': True, 'harvest_date': '2026-03-24', 'allergens': '', 'storage_tips': 'Each item has its own storage needs — roots keep in the fridge for a week, leafy greens are best within 3 days, and brassicas last 5–7 days. Unpack and store separately on arrival.', 'recipe_idea': 'Roast the roots with rapeseed oil and rosemary, wilt the greens with garlic and butter, and use the brassicas in a warming broth. Let what arrives decide the dish — that is the point of a veg box.', 'producer': p1, 'category': veg, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80'},

    # Bristol Artisan Bakery - Bread & Bakery
    {'name': 'Sourdough Loaf', 'description': 'Traditional sourdough bread with a blistered, mahogany crust and an open, chewy crumb. Slow-fermented for 18 hours using a 200-year-old Portuguese starter. Stone-milled Wiltshire heritage wheat.', 'price': '4.50', 'unit': 'per loaf', 'stock_quantity': 25, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Gluten', 'storage_tips': 'Store cut-side down on a wooden board, covered with a tea towel. Eat within 3 days or slice and freeze on delivery day. Avoid plastic bags — they soften the crust and ruin the texture.', 'recipe_idea': 'Thick-sliced and toasted, topped with soft scrambled eggs and a pinch of chilli flakes. Or tear into chunks and dip into quality extra-virgin olive oil with a grind of black pepper — this loaf needs no embellishment.', 'producer': p2, 'category': bread, 'farm_origin': 'Stokes Croft, Bristol', 'food_miles': '2', 'image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80'},
    {'name': 'Croissants (4 pack)', 'description': 'Buttery, flaky croissants with dozens of laminated layers, baked fresh every morning from 3am. Golden and crisp outside, pillowy and rich inside. Best eaten within two hours of collection.', 'price': '6.00', 'unit': 'pack of 4', 'stock_quantity': 15, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Gluten, Dairy, Eggs', 'storage_tips': 'Best eaten within 2 hours of baking. If keeping overnight, store in a paper bag and refresh in a 160°C oven for 5 minutes the next morning — they come back remarkably well.', 'recipe_idea': 'Split and fill with good ham and ripe Bristol Brie for a classic French sandwich, or layer with smoked salmon and soft cream cheese for something a little more indulgent on a slow weekend morning.', 'producer': p2, 'category': bread, 'farm_origin': 'Stokes Croft, Bristol', 'food_miles': '2', 'image_url': 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80'},
    {'name': 'Chocolate Muffins', 'description': 'Rich double-chocolate muffins with a cracked sugar dome and a molten dark chocolate centre. Made with 70% Ecuadorian cacao and Cotswold butter. Dangerously good at room temperature.', 'price': '5.50', 'unit': 'pack of 4', 'stock_quantity': 20, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Gluten, Dairy, Eggs', 'storage_tips': 'Keep in an airtight tin at room temperature for up to 3 days. Do not refrigerate — cold air dries out the crumb. Warm in a low oven at 140°C for 5 minutes before serving.', 'recipe_idea': 'Serve warm with a scoop of vanilla ice cream and a drizzle of salted caramel for an effortless dessert. Or split and fill with whipped cream and raspberries for an indulgent afternoon treat.', 'producer': p2, 'category': bread, 'farm_origin': 'Stokes Croft, Bristol', 'food_miles': '2', 'image_url': 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&q=80'},
    {'name': 'Artisan Pizza Base', 'description': 'Hand-stretched pizza dough, proved for 48 hours for an airy, charred, Neapolitan-style base. Made with Italian tipo 00 flour and our sourdough starter. Ready to top and bake at maximum oven heat.', 'price': '3.50', 'unit': 'each', 'stock_quantity': 18, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Gluten', 'storage_tips': 'Keep refrigerated and use within 2 days, or freeze immediately on delivery. Bring to room temperature for 30 minutes before shaping — cold dough tears and resists stretching.', 'recipe_idea': 'Top with crushed San Marzano tomatoes, torn mozzarella, and fresh basil, then bake in your hottest oven on a preheated tray or pizza stone for 8–10 minutes until the edges are charred and the cheese is bubbling.', 'producer': p2, 'category': bread, 'farm_origin': 'Stokes Croft, Bristol', 'food_miles': '2', 'image_url': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80'},

    # Meadow Dairy Co - Dairy
    {'name': 'Whole Milk', 'description': 'Unhomogenised whole milk from our Brown Swiss herd — the cream rises naturally to the top. Milked once a day, bottled within hours. Noticeably richer and more flavourful than anything from a supermarket shelf.', 'price': '1.80', 'unit': 'per litre', 'stock_quantity': 50, 'organic_certified': True, 'harvest_date': '2026-03-23', 'allergens': 'Milk', 'storage_tips': 'Keep refrigerated at all times and use within 4 days of delivery. Shake gently before pouring — the cream rises naturally to the top in unhomogenised milk, which is a sign of quality, not a fault.', 'recipe_idea': 'Use as the base for a proper rice pudding: simmer short-grain rice in whole milk with a split vanilla pod, a pinch of salt, and two tablespoons of sugar on the lowest heat for 45 minutes, stirring occasionally, until thick and fragrant.', 'producer': p3, 'category': dairy, 'farm_origin': 'Cotswolds, UK', 'food_miles': '40', 'image_url': 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80'},
    {'name': 'Farmhouse Cheddar', 'description': 'Cloth-bound cheddar aged for 12 months in our on-site maturing room. Firm and crumbly with a long, complex finish — notes of roasted hazelnut, warm caramel, and a clean acidic bite.', 'price': '7.50', 'unit': 'per 300g block', 'stock_quantity': 35, 'organic_certified': False, 'harvest_date': '2026-03-15', 'allergens': 'Milk', 'storage_tips': 'Wrap in waxed paper or a damp cloth — never plastic — and store in the coolest part of the fridge. Bring to room temperature 30 minutes before eating to release its full depth of flavour.', 'recipe_idea': 'Grate generously into a Welsh rarebit: melt with a splash of dark stout, a teaspoon of English mustard, and a dash of Worcestershire sauce, pour over thick sourdough toast and grill until golden and bubbling.', 'producer': p3, 'category': dairy, 'farm_origin': 'Cotswolds, UK', 'food_miles': '40', 'image_url': 'https://images.unsplash.com/photo-1624806992066-5ffcf7ca186b?w=600&q=80'},
    {'name': 'Free Range Eggs', 'description': 'Large eggs from our hens, who roam the Cotswold pasture freely between the dairy cows. Deep amber yolks and firm whites — outstanding fried, poached, or baked into a frittata.', 'price': '3.50', 'unit': 'per dozen', 'stock_quantity': 45, 'organic_certified': True, 'harvest_date': '2026-03-23', 'allergens': 'Eggs', 'storage_tips': 'Store at room temperature away from strong-smelling foods for up to 2 weeks, or refrigerate for up to 4 weeks. Always use the freshest eggs for frying or poaching where the yolk is the star.', 'recipe_idea': 'Soft-scramble in a heavy pan over very low heat with a generous knob of salted butter, stirring slowly with a spatula until barely set. Remove from the heat while still slightly glossy and serve immediately on sourdough toast.', 'producer': p3, 'category': dairy, 'farm_origin': 'Cotswolds, UK', 'food_miles': '40', 'image_url': 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=600&q=80'},
    {'name': 'Natural Yoghurt', 'description': 'Thick, set yoghurt made from our own whole milk and a live culture — nothing else. Rich and slightly tangy with a clean, clean finish. Perfect with fruit, granola, or eaten straight from the pot.', 'price': '2.80', 'unit': 'per 500g pot', 'stock_quantity': 30, 'organic_certified': True, 'harvest_date': '2026-03-22', 'allergens': 'Milk', 'storage_tips': 'Keep refrigerated and consume within 7 days of opening. A thin layer of liquid on the surface is completely normal — simply stir it back in before serving. Do not freeze.', 'recipe_idea': 'Layer in a glass with Mendip wildflower honey and crushed walnuts for a fast, satisfying breakfast. Or use as the base for a proper tzatziki: grate in cucumber, squeeze out excess moisture, add garlic, mint, and a drizzle of rapeseed oil.', 'producer': p3, 'category': dairy, 'farm_origin': 'Cotswolds, UK', 'food_miles': '40', 'image_url': 'https://images.unsplash.com/photo-1505253304499-671c55fb57fe?w=600&q=80'},
    {'name': 'Clotted Cream', 'description': 'Proper West Country clotted cream — thick, golden-crusted, and indulgently rich. Made by slowly scalding our unhomogenised milk to bring the cream to the surface. The essential companion to a proper scone.', 'price': '3.20', 'unit': 'per 200g pot', 'stock_quantity': 25, 'organic_certified': False, 'harvest_date': '2026-03-22', 'allergens': 'Milk', 'storage_tips': 'Keep refrigerated and consume within 5 days of opening. Preserve the golden crust on top until the moment of serving — it is the richest, most flavourful part.', 'recipe_idea': 'The only correct use for clotted cream is a proper West Country cream tea: a warm scone, a generous dollop of clotted cream, and a spoonful of strawberry jam. Cream first, then jam — that is the Devon way, and it is right.', 'producer': p3, 'category': dairy, 'farm_origin': 'Cotswolds, UK', 'food_miles': '40', 'image_url': 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80'},

    # Harbour Fresh Seafood
    {'name': 'Sea Bass Fillet', 'description': 'Line-caught sea bass from the Bristol Channel, landed that morning at Portishead. Delicate, sweet white flesh with a crisp silver skin that fries to perfection. One of the finest fish in British waters.', 'price': '9.50', 'unit': 'per 200g fillet', 'stock_quantity': 20, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Fish', 'storage_tips': 'Cook on the day of delivery for best results. If you must store it, lay on a plate skin-side up, cover with cling film, and keep in the coldest part of the fridge for no more than 24 hours.', 'recipe_idea': 'Score the skin in three places, season with sea salt, and fry skin-side down in a hot pan with rapeseed oil for 3–4 minutes without moving it. Flip for 60 seconds. Serve with wilted spinach, lemon, and a spoonful of aioli.', 'producer': p4, 'category': seafood, 'farm_origin': 'Bristol Channel, UK', 'food_miles': '10', 'image_url': 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80'},
    {'name': 'Whole Mackerel', 'description': 'Shimmering, firm mackerel caught fresh in the Bristol Channel by hand line. One of the most sustainable and nutritious fish available — rich in omega-3, with a bold, clean flavour that needs little more than salt and a hot pan.', 'price': '5.50', 'unit': 'per fish (approx. 300g)', 'stock_quantity': 25, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Fish', 'storage_tips': 'Cook on the day of delivery. If storing briefly, keep on ice or in the coldest part of your fridge for up to 24 hours. Whole fish keeps better ungutted — gut just before cooking.', 'recipe_idea': 'Score three times on each side, season generously with sea salt, and grill under a high heat for 4 minutes per side. Serve with a sharp gooseberry sauce or a simple herb vinaigrette — the acidity cuts through the richness beautifully.', 'producer': p4, 'category': seafood, 'farm_origin': 'Bristol Channel, UK', 'food_miles': '10', 'image_url': 'https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?w=600&q=80'},
    {'name': 'Fresh Crab Claws', 'description': 'Pot-caught brown crab claws from the Bristol Channel, cooked on the boat and chilled immediately. Sweet, firm crabmeat ready to crack and eat with a squeeze of lemon and good sourdough bread.', 'price': '12.00', 'unit': 'per 400g pack', 'stock_quantity': 15, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Crustaceans', 'storage_tips': 'Already cooked — keep refrigerated and eat within 24 hours of delivery. Do not refreeze once thawed. Crack and serve cold, or warm gently in a pan with a knob of butter and a splash of white wine.', 'recipe_idea': 'Crack the claws and pick out the meat, then toss with lemon zest, finely chopped parsley, a pinch of chilli, and a drizzle of rapeseed oil. Pile onto thick toasted sourdough with a wedge of lemon and eat immediately.', 'producer': p4, 'category': seafood, 'farm_origin': 'Bristol Channel, UK', 'food_miles': '10', 'image_url': 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80'},

    # Bristol Quality Meats
    {'name': 'Free-Range Chicken', 'description': 'Whole free-range chicken slow-grown over 81 days on Mendip pasture — more than double the industry standard. The meat is firm, flavourful, and deeply satisfying in a way that supermarket chicken simply cannot match.', 'price': '12.00', 'unit': 'per whole bird (approx. 1.8kg)', 'stock_quantity': 20, 'organic_certified': True, 'harvest_date': '2026-03-23', 'allergens': '', 'storage_tips': 'Keep refrigerated and cook within 2 days of delivery. Rest the bird for at least 15 minutes after roasting, loosely tented with foil, before carving — this makes an enormous difference to the juiciness.', 'recipe_idea': 'Rub generously with softened butter mixed with crushed garlic, lemon zest, and fresh rosemary from Somerset Herb Garden. Roast at 200°C for 20 minutes per kg plus 20 minutes. A slow-grown bird like this needs no further elaboration.', 'producer': p5, 'category': meat, 'farm_origin': 'Somerset, UK', 'food_miles': '20', 'image_url': 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&q=80'},
    {'name': 'Dry-Aged Ribeye Steak', 'description': 'A 28-day dry-aged ribeye from grass-fed Somerset beef — beautifully marbled, deeply flavoured, and unquestionably the finest steak you will cook at home this year. Best served medium-rare with nothing but salt and butter.', 'price': '16.50', 'unit': 'per 300g steak', 'stock_quantity': 12, 'organic_certified': False, 'harvest_date': '2026-03-22', 'allergens': '', 'storage_tips': 'Remove from packaging on arrival, place on a rack over a plate, and refrigerate uncovered for up to 24 hours — this helps develop a better crust. Bring to room temperature for at least 1 hour before cooking.', 'recipe_idea': 'Season heavily on both sides with flaky sea salt. Sear in a screaming hot cast-iron pan for 2.5 minutes per side. Add butter, a crushed garlic clove, and a sprig of thyme and baste for 1 minute. Rest for 5 minutes. Nothing else is needed.', 'producer': p5, 'category': meat, 'farm_origin': 'Somerset, UK', 'food_miles': '20', 'image_url': 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80'},
    {'name': 'Lamb Chops', 'description': 'Tender, pink lamb chops from West Country lambs grazed on herb-rich Somerset pasture. The fat is sweet and clean — do not trim it. Grill hard and fast, rest for two minutes, eat immediately.', 'price': '11.00', 'unit': 'per 400g (2 chops)', 'stock_quantity': 18, 'organic_certified': False, 'harvest_date': '2026-03-22', 'allergens': '', 'storage_tips': 'Keep refrigerated and cook within 2–3 days of delivery. The fat should be creamy white and firm — this is a mark of quality. Do not trim it before cooking; it bastes the meat as it renders.', 'recipe_idea': 'Marinate briefly in garlic, fresh rosemary, and rapeseed oil. Grill or pan-fry over high heat for 3–4 minutes per side. Rest for 2 minutes. Serve with a fresh mint sauce: chopped mint, white wine vinegar, a pinch of sugar, and a splash of water.', 'producer': p5, 'category': meat, 'farm_origin': 'Somerset, UK', 'food_miles': '20', 'image_url': 'https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&q=80'},

    # Pantry items
    {'name': 'Cold-Pressed Rapeseed Oil', 'description': 'Single-estate cold-pressed rapeseed oil from a farm in Wiltshire — golden, nutty, and with a higher smoke point than olive oil. Brilliant for roasting, frying, or dressing. Proudly British and grown within 50 miles.', 'price': '6.50', 'unit': 'per 500ml bottle', 'stock_quantity': 40, 'organic_certified': True, 'harvest_date': '2026-03-01', 'allergens': '', 'storage_tips': 'Store in a cool, dark cupboard away from heat and light. Once opened, use within 6 months for best flavour. Do not refrigerate — cold temperatures can cause it to cloud, though this does not affect quality.', 'recipe_idea': 'Whisk with cider vinegar, a teaspoon of Dijon mustard, and a drizzle of Mendip honey for a classic British-style salad dressing with a beautiful golden colour and nutty depth. Far better than any imported alternative.', 'producer': p1, 'category': pantry, 'farm_origin': 'Wiltshire, UK', 'food_miles': '35', 'image_url': 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80'},
    {'name': 'Fresh Egg Pasta', 'description': 'Handmade fresh egg pasta rolled and cut daily at the bakehouse — tagliatelle and pappardelle available. Made with Wiltshire heritage wheat and free-range eggs. Ready to cook in 2 minutes.', 'price': '3.50', 'unit': 'per 300g pack', 'stock_quantity': 25, 'organic_certified': False, 'harvest_date': '2026-03-24', 'allergens': 'Gluten, Eggs', 'storage_tips': 'Keep refrigerated and cook within 3 days of delivery. Fresh pasta cooks far faster than dried — 1–2 minutes in well-salted, vigorously boiling water. Do not overcook; it should still have a very slight bite.', 'recipe_idea': 'Toss in a cacio e pepe: cook the pasta, reserve a cup of starchy water, then work finely grated Parmesan and cracked black pepper into the water until it forms a glossy sauce. Add the pasta and toss vigorously. Extraordinary in under 10 minutes.', 'producer': p2, 'category': pantry, 'farm_origin': 'Stokes Croft, Bristol', 'food_miles': '2', 'image_url': 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=600&q=80'},
    {'name': 'Stone-Ground Spelt Flour', 'description': 'Stoneground wholegrain spelt flour from heritage grain grown in Wiltshire and milled to order. Nutty, slightly sweet, and nutritionally superior to modern wheat. Excellent for bread, pasta, and pancakes.', 'price': '3.20', 'unit': 'per 1kg bag', 'stock_quantity': 50, 'organic_certified': True, 'harvest_date': '2026-03-10', 'allergens': 'Gluten', 'storage_tips': 'Store in an airtight container in a cool, dark cupboard. Wholegrain flours contain natural oils that can turn rancid — use within 3 months of opening for best flavour and baking performance.', 'recipe_idea': 'Make a spelt soda bread: combine with bicarbonate of soda, salt, and Meadow buttermilk, shape into a round, score a deep cross on top, and bake at 200°C for 30–35 minutes. No kneading, no waiting — ready in under an hour.', 'producer': p2, 'category': pantry, 'farm_origin': 'Wiltshire, UK', 'food_miles': '40', 'image_url': 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80'},

    # Drinks
    {'name': 'Fresh Apple Juice', 'description': 'Cold-pressed juice from a blend of Somerset eating apples — crisp, naturally sweet, and cloudy with all its goodness intact. No added sugar, no water, no concentrates. Shake gently before pouring.', 'price': '3.20', 'unit': 'per 750ml bottle', 'stock_quantity': 30, 'organic_certified': True, 'harvest_date': '2026-03-24', 'allergens': '', 'storage_tips': 'Keep refrigerated once opened and consume within 5 days. The cloudy appearance is completely natural — it means the juice is unfiltered and full of goodness. Shake gently before pouring.', 'recipe_idea': 'Warm gently in a small pan with a cinnamon stick, two cloves, and a strip of orange peel for a soothing non-alcoholic winter warmer. Or use as the base for a sharp apple and cider vinegar dressing for autumnal salads.', 'producer': p6, 'category': drinks, 'farm_origin': 'Monmouth, Wales', 'food_miles': '32', 'image_url': 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80'},
    {'name': 'Meadow Buttermilk', 'description': 'The tangy, slightly thick liquid left after churning our cream into butter. A traditional ingredient in Irish soda bread and pancakes, and a superb tenderising marinade for chicken. Refreshing and surprisingly drinkable on its own.', 'price': '1.50', 'unit': 'per 500ml bottle', 'stock_quantity': 35, 'organic_certified': True, 'harvest_date': '2026-03-23', 'allergens': 'Milk', 'storage_tips': 'Keep refrigerated and use within 5 days of delivery. Buttermilk freezes well in ice cube trays for up to 3 months — useful when recipes only call for a small amount and you do not want to waste the rest.', 'recipe_idea': 'Make proper buttermilk pancakes: whisk with an egg, a knob of melted butter, and spelt flour until just combined (lumps are fine and expected). Cook in a dry pan over medium heat until bubbles form on the surface, then flip once. Serve with honey and fruit.', 'producer': p3, 'category': drinks, 'farm_origin': 'Cotswolds, UK', 'food_miles': '40', 'image_url': 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80'},

    # Wye Valley Orchard - Fruit
    {'name': "Cox's Orange Pippin Apples", 'description': 'The classic British dessert apple — crisp, aromatic, and perfectly balanced between sweet and sharp. Grown on 80-year-old trees on limestone soils above the River Wye.', 'price': '2.80', 'unit': 'per kg', 'stock_quantity': 120, 'organic_certified': True, 'harvest_date': '2026-03-20', 'allergens': '', 'storage_tips': 'Keep in the fridge for up to 2 weeks, or a cool dark place for up to 1 week. Bring to room temperature 30 minutes before eating — cold suppresses the floral aroma that makes this variety exceptional.', 'recipe_idea': 'Slice thinly and layer onto a cheese board alongside aged Farmhouse Cheddar, or bake whole — core each apple, fill with butter, brown sugar, and cinnamon, and roast at 180°C for 25 minutes for a simple, beautiful British pudding.', 'producer': p6, 'category': fruit, 'farm_origin': 'Monmouth, Wales', 'food_miles': '32', 'image_url': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80'},
    {'name': 'Williams Pears', 'description': 'Buttery, honey-sweet pears with a floral fragrance. A traditional heritage variety that has been grown in Britain since the 1700s. Best eaten when just yielding to gentle pressure.', 'price': '3.20', 'unit': 'per kg', 'stock_quantity': 80, 'organic_certified': True, 'harvest_date': '2026-03-19', 'allergens': '', 'storage_tips': 'Ripen at room temperature for 2–4 days until just yielding to gentle pressure near the stem. Once ripe, refrigerate and eat within 2–3 days. Pears ripen from the inside out — do not wait until they feel soft all over.', 'recipe_idea': 'Poach whole in a light sugar syrup with a split vanilla pod and a strip of lemon peel until a skewer slides in without resistance. Serve chilled with a spoonful of clotted cream or a scoop of vanilla ice cream.', 'producer': p6, 'category': fruit, 'farm_origin': 'Monmouth, Wales', 'food_miles': '32', 'image_url': 'https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600&q=80'},
    {'name': 'Sweet Cherries', 'description': 'Plump, dark red cherries bursting with natural sweetness. Hand-picked at the peak of ripeness from trees that are over 60 years old. Available for a short window each season — do not miss them.', 'price': '4.80', 'unit': 'per 400g punnet', 'stock_quantity': 40, 'organic_certified': True, 'harvest_date': '2026-03-22', 'allergens': '', 'storage_tips': 'Keep refrigerated with the stems on and eat within 3–4 days of delivery. Do not wash until just before eating — moisture on the skin speeds up spoilage significantly.', 'recipe_idea': 'Pit and fold into a classic clafoutis: whisk together eggs, flour, milk, sugar, and a splash of vanilla, pour over the cherries in a buttered dish, and bake at 180°C for 35–40 minutes until golden, puffed, and set. Dust with icing sugar and serve warm.', 'producer': p6, 'category': fruit, 'farm_origin': 'Monmouth, Wales', 'food_miles': '32', 'image_url': 'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=600&q=80'},
    {'name': 'Victoria Plums', 'description': 'The quintessential British plum — golden-red skin, juicy yellow flesh, and a gentle tartness that makes them perfect for crumbles, jams, or eating straight from the bag.', 'price': '3.50', 'unit': 'per kg', 'stock_quantity': 60, 'organic_certified': False, 'harvest_date': '2026-03-21', 'allergens': '', 'storage_tips': 'Allow to ripen at room temperature until fragrant and slightly soft. Once ripe, refrigerate and use within 3 days. If you want to make jam, pick them while they are still slightly firm — they hold their shape better during cooking.', 'recipe_idea': 'Halve, stone, and place cut-side up in a baking dish. Scatter with brown sugar and a star anise, then roast at 180°C for 20 minutes until tender and jammy. Serve warm over natural yoghurt or alongside a slice of almond cake.', 'producer': p6, 'category': fruit, 'farm_origin': 'Monmouth, Wales', 'food_miles': '32', 'image_url': 'https://images.unsplash.com/photo-1524855817330-8a9437ee5777?w=600&q=80'},
    {'name': 'Mixed Berry Box', 'description': 'A seasonal selection of whatever is at its absolute best from the orchard and hedgerow that week — blackberries, damsons, gooseberries, and more. The contents change with the season.', 'price': '5.50', 'unit': 'per 500g box', 'stock_quantity': 30, 'organic_certified': True, 'harvest_date': '2026-03-23', 'allergens': '', 'storage_tips': 'Keep refrigerated and eat within 2–3 days. Do not wash until ready to use. Lay a dry sheet of kitchen paper in the bottom of the box on arrival to absorb any moisture and slow spoilage.', 'recipe_idea': 'Simmer gently with a little caster sugar and a squeeze of lemon juice until the berries collapse into a loose, fragrant compote. Pour warm over porridge or natural yoghurt, or cool and spoon over pancakes throughout the week.', 'producer': p6, 'category': fruit, 'farm_origin': 'Monmouth, Wales', 'food_miles': '32', 'image_url': 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&q=80'},

    # Somerset Herb Garden - Vegetables
    {'name': 'Fresh Basil', 'description': 'Large-leafed Genovese basil, intensely fragrant and cut to order on the morning of delivery. Exceptional in pasta sauces, on pizza, or blended into fresh pesto with local olive oil.', 'price': '1.80', 'unit': 'per bunch', 'stock_quantity': 60, 'organic_certified': True, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Basil dislikes cold — never refrigerate it. Stand the bunch in a glass of water on the worktop, away from direct sunlight, like a small bunch of flowers. It will stay fresh for up to 5 days this way.', 'recipe_idea': 'Blend into a fresh pesto with toasted pine nuts, grated Parmesan, a clove of garlic, and cold-pressed rapeseed oil. More local, arguably more flavourful than the traditional olive oil version, and ready in under 5 minutes.', 'producer': p7, 'category': veg, 'farm_origin': 'Glastonbury, Somerset', 'food_miles': '28', 'image_url': 'https://images.unsplash.com/photo-1618375535959-08f7f89c3a30?w=600&q=80'},
    {'name': 'Rainbow Chard', 'description': 'Striking stems of red, yellow, orange, and white chard with tender, earthy leaves. Nutritious and versatile — sauté the stems like asparagus and wilt the leaves like spinach.', 'price': '2.20', 'unit': 'per bunch', 'stock_quantity': 50, 'organic_certified': True, 'harvest_date': '2026-03-26', 'allergens': '', 'storage_tips': 'Wrap in damp kitchen paper and store in the fridge for up to 4 days. Separate the stems from the leaves before cooking — they have quite different cooking times and both deserve attention.', 'recipe_idea': 'Sauté the stems in rapeseed oil with a crushed garlic clove and a pinch of chilli flakes for 5 minutes until tender, then add the leaves and wilt for 2 more minutes. Finish with a squeeze of lemon and serve alongside grilled sea bass or soft-scrambled eggs.', 'producer': p7, 'category': veg, 'farm_origin': 'Glastonbury, Somerset', 'food_miles': '28', 'image_url': 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=600&q=80'},
    {'name': 'Mixed Salad Leaves', 'description': 'A restaurant-quality mix of over 12 varieties of salad leaf — including mustard frills, red oak leaf, mizuna, and peppery rocket — cut fresh on delivery morning.', 'price': '2.50', 'unit': 'per 150g bag', 'stock_quantity': 70, 'organic_certified': True, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Keep refrigerated in the bag and eat within 3 days. Always dress at the very last moment — dressed leaves wilt within minutes. Handle gently; bruised leaves darken and lose their flavour quickly.', 'recipe_idea': 'Dress simply with a mustard vinaigrette: rapeseed oil, cider vinegar, a teaspoon of Dijon, and a pinch of salt, whisked together. Top with shaved Parmesan, toasted walnuts, and a handful of croutons for a lunch that punches well above its weight.', 'producer': p7, 'category': veg, 'farm_origin': 'Glastonbury, Somerset', 'food_miles': '28', 'image_url': 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=600&q=80'},
    {'name': 'Herb Bundle — Rosemary & Thyme', 'description': 'A generous bundle of woody rosemary and lemon thyme, perfect for roasting meats, seasoning stocks, or infusing oils. Dried bundles also available on request.', 'price': '1.50', 'unit': 'per bundle', 'stock_quantity': 80, 'organic_certified': True, 'harvest_date': '2026-03-26', 'allergens': '', 'storage_tips': 'Wrap loosely in slightly damp kitchen paper and refrigerate for up to 1 week. Alternatively, hang upside down in a warm, airy spot to dry — within a fortnight you will have fragrant dried herbs that keep for months.', 'recipe_idea': 'Tie a bundle and nestle it under the skin of a roasting chicken with butter and garlic, or steep a sprig of each in warm double cream for 20 minutes to make a fragrant infusion for a potato gratin or a cream sauce for lamb chops.', 'producer': p7, 'category': veg, 'farm_origin': 'Glastonbury, Somerset', 'food_miles': '28', 'image_url': 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&q=80'},
    {'name': 'Purple Kale', 'description': 'Deep purple kale with a slightly sweeter, more tender flavour than green varieties. Excellent massaged raw in salads, roasted into crisps, or wilted into a winter broth.', 'price': '2.00', 'unit': 'per bunch', 'stock_quantity': 55, 'organic_certified': True, 'harvest_date': '2026-03-25', 'allergens': '', 'storage_tips': 'Keep refrigerated and use within 4–5 days. Remove the tough central stems before cooking. If using raw in a salad, massage the leaves firmly with a little rapeseed oil and a pinch of salt for 2 minutes to soften the texture dramatically.', 'recipe_idea': 'Tear into bite-sized pieces, toss with rapeseed oil and a pinch of flaky sea salt, spread in a single layer on a baking tray, and roast at 180°C for 10–12 minutes until crisp. Season immediately with smoked paprika. Completely addictive.', 'producer': p7, 'category': veg, 'farm_origin': 'Glastonbury, Somerset', 'food_miles': '28', 'image_url': 'https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=600&q=80'},

    # Mendip Hive & Preserves - Preserves & Pantry
    {'name': 'Mendip Wildflower Honey', 'description': 'Raw, unfiltered honey from bees foraging across Mendip wildflower meadows and limestone grassland. Each jar is a snapshot of a particular meadow at a particular moment — no two batches are identical.', 'price': '7.50', 'unit': 'per 340g jar', 'stock_quantity': 45, 'organic_certified': False, 'harvest_date': '2026-02-10', 'allergens': 'Honey', 'storage_tips': 'Store at room temperature with the lid tightly closed. Honey never expires. If it crystallises — which is a sign of pure, unprocessed honey — stand the jar in warm water for a few minutes and it will return to a liquid state.', 'recipe_idea': 'Place a whole round of Bristol Brie in a small baking dish, drizzle generously with this honey, and scatter over crushed walnuts. Bake at 180°C for 8–10 minutes until the cheese is molten. Serve immediately with toasted sourdough for dipping.', 'producer': p8, 'category': preserves, 'farm_origin': 'Cheddar, Somerset', 'food_miles': '18', 'image_url': 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80'},
    {'name': 'Strawberry & Vanilla Jam', 'description': 'Summer strawberries from a farm two miles down the road, cooked slowly with vanilla bean and just enough sugar to let the fruit speak for itself. No artificial pectin, no shortcuts.', 'price': '4.50', 'unit': 'per 280g jar', 'stock_quantity': 35, 'organic_certified': False, 'harvest_date': '2026-01-15', 'allergens': '', 'storage_tips': 'Store in a cool, dark cupboard before opening. Once opened, refrigerate and use within 6 weeks. Always use a clean, dry spoon to avoid introducing moisture that can cause mould to form on the surface.', 'recipe_idea': 'Sandwich generously between two layers of a classic Victoria sponge with softly whipped double cream for the quintessential British afternoon tea centrepiece. Or simply spread thickly on warm sourdough toast with a layer of clotted cream underneath.', 'producer': p8, 'category': preserves, 'farm_origin': 'Cheddar, Somerset', 'food_miles': '18', 'image_url': 'https://images.unsplash.com/photo-1490323815596-d9f9e19b37ca?w=600&q=80'},
    {'name': 'Seville Orange Marmalade', 'description': 'Made each January during the brief Seville orange season. Thick-cut, intensely bitter-sweet, and deeply aromatic. The kind of marmalade that makes a plain piece of toast into something worth waking up for.', 'price': '4.80', 'unit': 'per 300g jar', 'stock_quantity': 28, 'organic_certified': False, 'harvest_date': '2026-01-20', 'allergens': '', 'storage_tips': 'Store in a cool, dark cupboard for up to a year before opening. Once opened, refrigerate and use within 3 months. The bitterness mellows very slightly as the jar ages — opening it in February rather than January is not a mistake.', 'recipe_idea': 'Mix two tablespoons with a splash of soy sauce and a thumb of fresh ginger, then use as a glaze for roast duck legs or pork belly — the bitter citrus cuts through the fat magnificently. Or simply spread thickly on sourdough with good salted butter at breakfast.', 'producer': p8, 'category': preserves, 'farm_origin': 'Cheddar, Somerset', 'food_miles': '18', 'image_url': 'https://images.unsplash.com/photo-1605548230624-8d2d0419c664?w=600&q=80'},
    {'name': 'Blackcurrant Preserve', 'description': 'Intensely fruity blackcurrant preserve with a deep, almost wine-like richness. Made from blackcurrants grown in Margaret\'s kitchen garden. Outstanding on scones, stirred into yoghurt, or spooned over vanilla ice cream.', 'price': '4.20', 'unit': 'per 280g jar', 'stock_quantity': 30, 'organic_certified': False, 'harvest_date': '2025-08-14', 'allergens': '', 'storage_tips': 'Keep in a cool, dark cupboard before opening. Once opened, refrigerate and use within 6 weeks. The deep purple colour will stain readily — handle with care around light fabrics and wooden surfaces.', 'recipe_idea': 'Stir a generous spoonful into natural yoghurt with a drizzle of wildflower honey for a quick, deeply flavoured breakfast or dessert. Or warm gently and pour over good vanilla ice cream for a rich, grown-up sundae that takes less than 5 minutes to prepare.', 'producer': p8, 'category': preserves, 'farm_origin': 'Cheddar, Somerset', 'food_miles': '18', 'image_url': 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80'},
    {'name': 'Chilli & Apple Jelly', 'description': 'A fiery, jewel-bright jelly made from Bramley apples and fresh red chillies. A perfect partner for cheese, cold meats, or grilled chicken. The heat builds slowly — be warned.', 'price': '4.00', 'unit': 'per 220g jar', 'stock_quantity': 25, 'organic_certified': False, 'harvest_date': '2025-10-05', 'allergens': '', 'storage_tips': 'Store in a cool, dark cupboard before opening. Once open, refrigerate and use within 2 months. The heat intensifies slightly as the jar sits open — start with less than you think you need if you are heat-sensitive.', 'recipe_idea': 'Place a generous spoonful alongside a cheese board — it is exceptional with mature cheddar, goat\'s cheese, and crackers. Or melt into a hot pan after searing chicken thighs to create a quick, glossy sauce with fruit sweetness and building heat.', 'producer': p8, 'category': preserves, 'farm_origin': 'Cheddar, Somerset', 'food_miles': '18', 'image_url': 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=600&q=80'},

    # Clifton Fine Cheese - Dairy
    {'name': 'Bristol Brie', 'description': 'A soft, bloomy-rind brie-style cheese made from full-fat pasteurised cow\'s milk sourced from a single Somerset farm. Creamy and mushroomy at the rind, buttery and flowing at the centre when perfectly ripe.', 'price': '6.80', 'unit': 'per 200g round', 'stock_quantity': 20, 'organic_certified': False, 'harvest_date': '2026-03-18', 'allergens': 'Milk', 'storage_tips': 'Unwrap and rewrap loosely in waxed paper before refrigerating — it needs to breathe. Remove from the fridge at least 1 hour before eating; cold cheese has almost no flavour. Consume within 5 days of purchase.', 'recipe_idea': 'Place the whole round in a small baking dish, drizzle with Mendip wildflower honey, and scatter over crushed walnuts and a pinch of fresh thyme. Bake at 180°C for 10 minutes until molten at the centre. Serve immediately with sourdough bread for dipping.', 'producer': p9, 'category': dairy, 'farm_origin': 'Clifton, Bristol', 'food_miles': '3', 'image_url': 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80'},
    {'name': 'Clifton Blue', 'description': 'A bold, buttery blue cheese with a natural grey-green rind and a creamy paste shot through with blue-grey veining. The flavour is rich and savoury without being overpowering — a blue for people who think they don\'t like blue cheese.', 'price': '8.50', 'unit': 'per 250g wedge', 'stock_quantity': 15, 'organic_certified': False, 'harvest_date': '2026-03-10', 'allergens': 'Milk', 'storage_tips': 'Wrap in foil rather than cling film to allow the cheese to breathe and continue maturing. Keep in the warmest part of the fridge and bring to room temperature for at least 45 minutes before serving — this is non-negotiable with a blue cheese.', 'recipe_idea': 'Crumble generously over a warm salad of roasted Williams pears, toasted walnuts, and dressed rocket for a classic combination that never fails. Or stir into a pan sauce with double cream and fresh thyme for a deeply satisfying pasta sauce in under 10 minutes.', 'producer': p9, 'category': dairy, 'farm_origin': 'Clifton, Bristol', 'food_miles': '3', 'image_url': 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600&q=80'},
    {'name': "Somerset Goat's Cheese", 'description': 'Fresh, snow-white goat\'s cheese with a clean, citrusy flavour and a light, mousse-like texture. Made from milk collected weekly from a small goat dairy near Wells. Excellent crumbled over salad or baked in filo pastry.', 'price': '5.50', 'unit': 'per 150g log', 'stock_quantity': 22, 'organic_certified': False, 'harvest_date': '2026-03-21', 'allergens': 'Milk', 'storage_tips': 'Keep refrigerated, tightly wrapped in waxed paper, and use within 5 days of delivery. Goat\'s cheese absorbs surrounding flavours readily — store it away from anything strongly scented in the fridge.', 'recipe_idea': 'Slice into rounds, brush with rapeseed oil, press each side into crushed mixed peppercorns, and pan-fry for 1 minute per side until golden. Serve warm on a bed of mixed salad leaves dressed with a honey and cider vinegar dressing. Simple and deeply satisfying.', 'producer': p9, 'category': dairy, 'farm_origin': 'Clifton, Bristol', 'food_miles': '3', 'image_url': 'https://images.unsplash.com/photo-1559561853-08451507cbe7?w=600&q=80'},
    {'name': 'Smoked Applewood Cheddar', 'description': 'A firm, crumbly cheddar cold-smoked over applewood chips for six hours, giving it a subtle, sweet smokiness that complements the sharp, mature flavour of the cheese. Spectacular in a toasted sandwich.', 'price': '7.00', 'unit': 'per 250g block', 'stock_quantity': 18, 'organic_certified': False, 'harvest_date': '2026-03-05', 'allergens': 'Milk', 'storage_tips': 'Wrap in waxed paper and store in the fridge. Bring to room temperature for 30 minutes before serving on a cheese board to let the smoke and aged flavours open up fully. Use within 2 weeks of purchase.', 'recipe_idea': 'Grate generously into a toasted sandwich on thick sourdough with a thin spread of Dijon mustard and a few slices of pickled onion. Press in a heavy pan over medium heat until both sides are deeply golden and the cheese is completely molten. Extraordinary.', 'producer': p9, 'category': dairy, 'farm_origin': 'Clifton, Bristol', 'food_miles': '3', 'image_url': 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=600&q=80'},

    # Severn Cordial Co. - Drinks & Pantry
    {'name': 'Elderflower Cordial', 'description': 'Made from elderflower heads foraged from the hedgerows of the Wye Valley each June. Floral, delicate, and deeply refreshing diluted with sparkling water or used in cocktails and dressings.', 'price': '5.50', 'unit': 'per 500ml bottle', 'stock_quantity': 40, 'organic_certified': False, 'harvest_date': '2025-06-12', 'allergens': '', 'storage_tips': 'Keep refrigerated once opened and use within 6 weeks. Undiluted cordial freezes well in ice cube trays for up to 6 months — add a cube or two directly to sparkling water for an instant summer drink at any time of year.', 'recipe_idea': 'Mix 1 part cordial with 4 parts sparkling water over ice and garnish with a sprig of fresh mint and a slice of cucumber. Or add a generous splash to a glass of chilled Prosecco with a twist of lemon peel for an effortless garden party aperitif.', 'producer': p10, 'category': drinks, 'farm_origin': 'Chepstow, Monmouthshire', 'food_miles': '22', 'image_url': 'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=600&q=80'},
    {'name': 'Apple & Ginger Juice', 'description': 'Fresh-pressed Wye Valley apples blended with cold-pressed ginger root. No water added, no sugar added — just the pure, fiery-sweet flavour of two ingredients at their best. Shake before drinking.', 'price': '4.20', 'unit': 'per 750ml bottle', 'stock_quantity': 35, 'organic_certified': False, 'harvest_date': '2026-03-15', 'allergens': '', 'storage_tips': 'Keep refrigerated and shake well before pouring — the natural sediment settles at the bottom, which is a sign of quality, not a fault. Consume within 5 days of opening for best flavour.', 'recipe_idea': 'Warm gently with a cinnamon stick, two cloves, and a strip of orange peel for a soothing non-alcoholic winter warmer. Or whisk cold with cider vinegar, Dijon mustard, and rapeseed oil for a sharp, spiced dressing that works beautifully on roasted vegetable salads.', 'producer': p10, 'category': drinks, 'farm_origin': 'Chepstow, Monmouthshire', 'food_miles': '22', 'image_url': 'https://images.unsplash.com/photo-1576673442511-7e39b6545c87?w=600&q=80'},
    {'name': 'Raspberry Lemonade', 'description': 'Pressed raspberries from a farm in the Forest of Dean, balanced with lemon juice and a light sugar syrup. Bright pink, sharply fruity, and far more interesting than anything in a supermarket fridge.', 'price': '3.80', 'unit': 'per 500ml bottle', 'stock_quantity': 30, 'organic_certified': False, 'harvest_date': '2026-03-10', 'allergens': '', 'storage_tips': 'Keep refrigerated and consume within 5 days of opening. Shake gently before pouring. Serve very cold over plenty of ice — the flavour is sharper and more vivid when properly chilled.', 'recipe_idea': 'Pour over crushed ice with a handful of fresh mint leaves and a squeeze of extra lemon for a vibrant, refreshing summer drink. Or use as a mixer — it pairs exceptionally well with gin or elderflower vodka for a fruity, sharp cocktail that looks as good as it tastes.', 'producer': p10, 'category': drinks, 'farm_origin': 'Chepstow, Monmouthshire', 'food_miles': '22', 'image_url': 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=600&q=80'},
    {'name': 'Sloe Berry Syrup', 'description': 'Hand-foraged sloe berries from Wye Valley hedgerows, slow-cooked into a rich, tart, deeply flavoured syrup. Stir into sparkling water, pour over ice cream, or use as a mixer in gin-based cocktails.', 'price': '6.00', 'unit': 'per 250ml bottle', 'stock_quantity': 20, 'organic_certified': False, 'harvest_date': '2025-10-18', 'allergens': '', 'storage_tips': 'Keep refrigerated once opened and use within 3 months. The high sugar content preserves it well. Any slight thickening in the cold is completely normal and will loosen when brought to room temperature for a few minutes.', 'recipe_idea': 'Add a generous tablespoon to a glass of sparkling water over ice for a tart, hedgerow-flavoured soft drink. Or stir into a gin and tonic — the dark, fruity depth it adds is a revelation. Also outstanding drizzled over vanilla ice cream directly from the bottle.', 'producer': p10, 'category': pantry, 'farm_origin': 'Chepstow, Monmouthshire', 'food_miles': '22', 'image_url': 'https://images.unsplash.com/photo-1571066811602-716837d681de?w=600&q=80'},

    # ── Rescue Market surplus listings ────────────────────────────────────────
    {'name': 'Imperfect Carrots', 'description': 'Oddly shaped but perfectly delicious carrots from this morning\'s harvest. Taste identical to our regular crop — just a bit wonky. Heavily discounted to avoid waste.', 'price': '1.00', 'unit': 'per kg', 'stock_quantity': 30, 'organic_certified': True, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Keep in a sealed bag in the fridge. Use within 5 days.', 'recipe_idea': 'Perfect for roasting, soups, or a quick stir-fry — the shape makes no difference once they hit the pan.', 'producer': p1, 'category': veg, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&q=80'},
    {'name': 'Overripe Bananas', 'description': 'Spotted bananas that are past their eating peak but absolutely ideal for baking. Naturally sweeter when overripe — the best banana bread you will ever make starts here.', 'price': '0.80', 'unit': 'per bunch', 'stock_quantity': 20, 'organic_certified': False, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Use today or tomorrow for baking. Can be peeled and frozen for up to 3 months.', 'recipe_idea': 'Mash three bananas with butter, sugar, egg, and flour for a quick banana bread — bake at 180°C for 50 minutes. No mixer needed.', 'producer': p1, 'category': fruit, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=600&q=80'},
    {'name': 'Bumper Crop Courgettes', 'description': 'An unexpectedly large courgette harvest this week means we have far more than we can sell at full price. Perfectly fresh, just surplus to requirements.', 'price': '1.50', 'unit': 'per kg', 'stock_quantity': 50, 'organic_certified': True, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Keep in the fridge and use within 4 days. Do not freeze raw.', 'recipe_idea': 'Slice into ribbons with a peeler and toss raw with lemon, olive oil, and Parmesan for a 5-minute courgette salad. Or grate into fritters with egg and spelt flour.', 'producer': p1, 'category': veg, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1612257416648-58b0f78fd0b0?w=600&q=80'},
    {'name': 'Surplus Heritage Tomatoes', 'description': 'A restaurant order was cancelled this morning, leaving us with a large quantity of vine-ripened heritage tomatoes. Must go today — deeply discounted.', 'price': '1.50', 'unit': 'per kg', 'stock_quantity': 25, 'organic_certified': True, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Store at room temperature and use within 2 days. Never refrigerate — it kills the flavour.', 'recipe_idea': 'Halve, season with salt, drizzle with oil, and roast at 200°C for 25 minutes until collapsed and jammy. Extraordinary on toast or stirred into pasta.', 'producer': p1, 'category': veg, 'farm_origin': 'Somerset, UK', 'food_miles': '25', 'image_url': 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&q=80'},
    {'name': 'End-of-Week Spinach', 'description': 'Cut this morning but needs to move today. Perfectly fresh spinach at a steep discount — there is nothing wrong with it except that we cut too much.', 'price': '0.70', 'unit': 'per bag (200g)', 'stock_quantity': 40, 'organic_certified': True, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Keep refrigerated and use today or tomorrow. Do not wash until ready to cook.', 'recipe_idea': 'Wilt with garlic butter and a pinch of nutmeg as a side dish, or blend raw into a smoothie with banana and apple for a quick green boost.', 'producer': p7, 'category': veg, 'farm_origin': 'Glastonbury, Somerset', 'food_miles': '28', 'image_url': 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80'},
    {'name': 'Windfall Bramley Apples', 'description': 'Strong winds last night brought down a large number of Bramley apples before they were fully ready. Ideal for cooking — they still break down beautifully into a fluffy purée.', 'price': '1.20', 'unit': 'per kg', 'stock_quantity': 60, 'organic_certified': False, 'harvest_date': '2026-03-27', 'allergens': '', 'storage_tips': 'Store in a cool, dark place and use within 1 week. Windfalls bruise more easily — handle gently and use any damaged ones first.', 'recipe_idea': 'Classic apple crumble: peel and slice 4 apples, toss with cinnamon and brown sugar, top with an oat and butter crumble, bake at 180°C for 35 minutes.', 'producer': p6, 'category': fruit, 'farm_origin': 'Monmouth, Wales', 'food_miles': '32', 'image_url': 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&q=80'},
]

for pd in products_data:
    pd['price'] = Decimal(pd['price'])
    if 'food_miles' in pd:
        pd['food_miles'] = Decimal(pd['food_miles'])
    Product.objects.create(**pd)

print(f"Created: {User.objects.count()} users, {ProducerProfile.objects.count()} profiles, {Category.objects.count()} categories, {Product.objects.count()} products")
print("Test accounts:")
print("  Admin:    admin@bristol.ac.uk / admin1234")
print("  Customer: customer@test.com / test1234")
print("  Producer: green@farm.co.uk / test1234")