# Generated by Django 6.0.2 on 2026-03-24 22:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('stock_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('allergens', models.TextField(blank=True)),
                ('organic_certified', models.BooleanField(default=False)),
                ('harvest_date', models.DateField()),
                ('farm_origin', models.CharField(blank=True, default='', help_text="e.g. 'Bristol, UK'", max_length=255)),
                ('food_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated food miles for this product', max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_available'], name='products_pr_categor_c898cc_idx'), models.Index(fields=['producer', 'is_available'], name='products_pr_produce_4ad597_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='product_stock_non_negative'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'), models.CheckConstraint(condition=models.Q(('available_from__isnull', True), ('available_to__isnull', True), ('available_from__lte', models.F('available_to')), _connector='OR'), name='product_season_range_valid')],
            },
        ),
    ]