# Generated by Django 6.0.2 on 2026-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farm_origin',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Bristol, UK'", max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='food_miles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated food miles for this product', max_digits=7, null=True),
        ),
    ]
