# Generated by Django 6.0.2 on 2026-03-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe_idea',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_tips',
            field=models.TextField(blank=True),
        ),
    ]
