# Generated by Django 6.0.2 on 2026-05-04 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_recipe_idea_product_storage_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
