# Generated by Django 6.0.2 on 2026-03-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producerprofile',
            old_name='postcode',
            new_name='store_postcode',
        ),
    ]
