# Generated by Django 6.0.2 on 2026-05-07 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_harvest_date'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_product_customer_review',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_product_847b15_idx',
            old_name='reviews_revi_product_created_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_custome_13ae16_idx',
            old_name='reviews_revi_custome_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'customer')},
        ),
    ]
