# Generated by Django 5.2.13 on 2026-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
