# Generated by Django 5.2.1 on 2026-05-07 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_type_order_organisation_name_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySettlementCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, unique=True)),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('num_settlements', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['-week_start'], name='payments_we_week_st_51a1bd_idx')],
            },
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.weeklysettlementcycle'),
        ),
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('producer_order', 'settlement_cycle')},
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['producer', '-created_at'], name='payments_se_produce_ece8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['status', '-created_at'], name='payments_se_status_840214_idx'),
        ),
    ]
