# Generated by Django 6.0.2 on 2026-04-21 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_recipe_idea_product_storage_tips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('model_file_path', models.CharField(max_length=500)),
                ('model_type', models.CharField(choices=[('quality_classifier', 'Quality Classifier'), ('recommendation', 'Recommendation Engine')], max_length=30)),
                ('architecture', models.CharField(blank=True, help_text='e.g. MobileNetV2, ResNet50, CollabFilter', max_length=100)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changelog', models.TextField(blank=True, help_text='What changed from the previous version.')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('test_samples', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('grade_a_accuracy', models.FloatField(blank=True, null=True)),
                ('grade_b_accuracy', models.FloatField(blank=True, null=True)),
                ('grade_c_accuracy', models.FloatField(blank=True, null=True)),
                ('confusion_matrix_json', models.TextField(blank=True, help_text='JSON-serialised 3×3 confusion matrix [A, B, C].')),
                ('override_rate', models.FloatField(blank=True, help_text='Percentage of recommendations overridden by users.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('figures_path', models.CharField(blank=True, help_text='Directory path for generated evaluation figures.', max_length=500)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='ai_service.mlmodel')),
            ],
            options={
                'verbose_name': 'Model Evaluation Report',
                'verbose_name_plural': 'Model Evaluation Reports',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed'), ('added_to_cart', 'Added to Cart'), ('purchased', 'Purchased'), ('reordered', 'Reordered'), ('overrode_recommendation', 'Overrode Recommendation'), ('dismissed_recommendation', 'Dismissed Recommendation')], max_length=30)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('session_id', models.CharField(blank=True, help_text='Groups interactions belonging to one browsing session.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Interaction',
                'verbose_name_plural': 'Product Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('colour_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('size_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ripeness_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('overall_grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('grad_cam_image_url', models.CharField(blank=True, default='', help_text='Path to Grad-CAM heatmap image for XAI visualisation.', max_length=500)),
                ('auto_discount_applied', models.BooleanField(default=False)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0-mock', max_length=50)),
                ('is_mock', models.BooleanField(default=True, help_text='True if assessed by mock model; False if assessed by real CNN.')),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to='products.product')),
            ],
            options={
                'verbose_name': 'Quality Assessment',
                'verbose_name_plural': 'Quality Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_filter_applied', models.BooleanField(default=True)),
                ('algorithm_used', models.CharField(default='hybrid_quality_aware_collaborative', max_length=100)),
                ('frequency_weight', models.FloatField(default=1.0)),
                ('collaborative_weight', models.FloatField(default=0.3)),
                ('quality_boost_applied', models.BooleanField(default=False)),
                ('products_suppressed', models.IntegerField(default=0, help_text='Number of Grade C products suppressed from this run.')),
                ('products_boosted', models.IntegerField(default=0, help_text='Number of Grade A products boosted in this run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
                ('recommended_products', models.ManyToManyField(blank=True, related_name='recommendation_logs', to='products.product')),
            ],
            options={
                'verbose_name': 'Recommendation Log',
                'verbose_name_plural': 'Recommendation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
