# Generated by Django 6.0.2 on 2026-05-07 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('orders', '0002_order_order_type_order_organisation_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='couponuse',
            name='unique_coupon_user_order',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='discounts_c_code_3b6115_idx',
            old_name='discounts_co_code_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='discounts_c_is_acti_9d60f4_idx',
            old_name='discounts_co_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='couponuse',
            new_name='discounts_c_coupon__efb3b6_idx',
            old_name='discounts_co_coupon_user_idx',
        ),
        migrations.RenameIndex(
            model_name='couponuse',
            new_name='discounts_c_user_id_efbca7_idx',
            old_name='discounts_co_user_used_idx',
        ),
        migrations.AlterUniqueTogether(
            name='couponuse',
            unique_together={('coupon', 'user', 'order')},
        ),
    ]
