# Generated by Django 5.2.13 on 2026-04-13 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups orders from the same checkout session'),
        ),
        migrations.AddField(
            model_name='order',
            name='producer_id',
            field=models.CharField(db_index=True, default='', help_text='Producer who fulfils this order', max_length=36),
        ),
        migrations.AddField(
            model_name='order',
            name='producer_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
