# Generated by Django 6.0.2 on 2026-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brfn_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commission Record', 'verbose_name_plural': 'Commission Records'},
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='producer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SETTLED', 'Settled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='order_ref',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
